### ISSUE TITLE
Bug after installing Plugin

### ISSUE THREAD

**Issue by evanomondi** [kingflamez/Rave-Engine-Theme-Plugin#1]
Hi, good job on the plugin. 
Am getting the error bellow right after clicking activate. This error only appears when I try loging in to the admin section.

at first I was getting this error:
Parse error: syntax error, unexpected ',', expecting ')' in /home/peepo/public_html/freelance/wp-content/plugins/Rave-Engine-Theme-Plugin-master/ae_rave.php on line 74

Then I cleared the commas after which the below error came.

Fatal error: Uncaught Error: Class 'AE_dropdown' not found in /home/peepo/public_html/freelance/wp-content/themes/freelanceengine/includes/aecore/fields/groups.php:48 Stack trace: #0 /home/peepo/public_html/freelance/wp-content/themes/freelanceengine/includes/aecore/fields/sections.php(42): AE_group->__construct(Array, Array, Object(AE_Options)) #1 /home/peepo/public_html/freelance/wp-content/plugins/Rave-Engine-Theme-Plugin-master/ae_rave.php(104): AE_section->__construct(Array, Array, Object(AE_Options)) #2 /home/peepo/public_html/freelance/wp-includes/class-wp-hook.php(286): ae_rave_add_settings(Array) #3 /home/peepo/public_html/freelance/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #4 /home/peepo/public_html/freelance/wp-content/themes/freelanceengine/includes/admin.php(3205): apply_filters('ae_admin_menu_p...', Array) #5 /home/peepo/public_html/freelance/wp-includes/class-wp-hook.php(286): ET_Admin->admin_setup('') #6 /home/peepo/public_html/freelance/wp-includes/class-wp-hook.php(310): WP_Hook-> in /home/peepo/public_html/freelance/wp-content/themes/freelanceengine/includes/aecore/fields/groups.php on line 48

**Comment by evanomondi** [comment]
at first, I was getting this error:
Parse error: syntax error, unexpected ',', expecting ')' in /home/peepo/public_html/freelance/wp-content/plugins/Rave-Engine-Theme-Plugin-master/ae_rave.php on line 74

Then I cleared the commas after which the below error came.

**Comment by evanomondi** [comment]
I have temporarily made the dropdowns into text and the error disappeared. Though now am dealing with an issue where there is no select button to select the rave payment option
